<?php
/**
 * @copyright  Copyright (c) 2013 AITOC, Inc. 
 * @license License agreement could be found at the root folder of this package
 */
 ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('aitloadmon')->__('Avg Load / Max Load for the selected period by groups');?></h4>
    </div>
    <div class="fieldset">
        <div id="graph2" style="height: 200px; width: 1000px;"></div>
    </div>
</div>
<script type="text/javascript">
    var graph2 = new Grafico.HorizontalBarGraphCustom($('graph2'), {
        <?php echo $this->getBarGraphData(); ?>
            },
            {
                labels:               <?php echo $this->getBarLabels($this->getCompare()); ?>,
                show_ticks:           false,
                compare_mode:         <?php echo (int)$this->getCompare();?>,
                vertical_label_unit : "s",
                colors:               {
                    max_load:       '#A0151E',
                    avg_load:       ['#877D1E',"#6016CA","#1680CA","#F5861A","#1B7B00"]
                }
            }
    );
</script>