<?php
/**
 * @copyright  Copyright (c) 2013 AITOC, Inc. 
 * @license License agreement could be found at the root folder of this package
 */
 ?>
<style>
    .linegraph_check
    {
        margin-right: 5px;
        margin-left: 25px;
    }
</style>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('aitloadmon')->__(($this->getType()=='max')?'MAXIMUM':'AVERAGE').Mage::helper('aitloadmon')->__(' LOAD for the selected period by groups and time');?></h4>
    </div>
    <div class="fieldset">
        <div><?php echo Mage::helper('aitloadmon')->__('Show graphs for:'); ?><?php echo $this->getCheckBoxes(); ?></div>
        <div id="graph1" style="height: 340px; width: 1000px;"></div>
        <?php if($this->getCompare()):?><div id="graph1compare" style="height: 340px; width: 1000px;"></div><?php endif;?>
    </div>
</div>
<script type="text/javascript">
    var lineGraphs = [];
    function toggleLines(obj)
    {
        var graphId = $(obj).getAttribute('rel');
        if(lineGraphs[graphId])
        {
            if(!$(obj).checked)
            {
                lineGraphs[graphId].each(function(element){element.hide()});
            }
            else
            {
                lineGraphs[graphId].each(function(element){element.show()});
            }
        }
    }
    <?php $lineGraph = $this->getLineGraphData(); ?>
    var graph1 = new Grafico.LineGraphCustom($('graph1'),
            {
            <?php echo $lineGraph['data']; ?>
            },
            {
                markers :                 "value",
                grid :                    true,
                draw_axis :               true,
                plot_padding :            0,
                stroke_width :            2,
                show_vertical_labels :    true,
                show_horizontal_labels :  true,
                vertical_label_unit:      's',
                label_rotation :        0,
                labels :                <?php echo $lineGraph['labels']; ?>,
                dot_labels :            <?php echo $lineGraph['dot_labels']; ?>,
                label_sizes :           {<?php echo $lineGraph['dataSize']; ?>},
                hover_color :             "#000",
                hover_text_color :        "#fff",
                opacity:                1,
                colors: {
                    other:          "#877D1E",
                    cms:            "#6016CA",
                    checkout:       "#1680CA",
                    catalogsearch:  "#F5861A",
                    catalog:        "#1B7B00"
                },
                datalabels : {
                    other:          "Other pages",
                    cms:            "CMS pages",
                    checkout:       "Checkout pages",
                    catalogsearch:  "Search pages",
                    catalog:        "Catalog pages"
                }
            });

    <?php if($this->getCompare()):?>
        <?php $lineGraph = $this->getLineGraphDataCompared(); ?>
    var graph1 = new Grafico.LineGraphCustom($('graph1compare'),
            {
                <?php echo $lineGraph['data']; ?>
            },
            {
                markers :                 "value",
                grid :                    true,
                draw_axis :               true,
                plot_padding :            0,
                stroke_width :            2,
                show_vertical_labels :    true,
                show_horizontal_labels :  true,
                label_rotation :        0,
                labels :                <?php echo $lineGraph['labels']; ?>,
                dot_labels :            <?php echo $lineGraph['dot_labels']; ?>,
                label_sizes :           {<?php echo $lineGraph['dataSize']; ?>},
                hover_color :             "#000",
                hover_text_color :        "#fff",
                opacity:                0.5,
                colors: {
                    other:          "#877D1E",
                    cms:            "#6016CA",
                    checkout:       "#1680CA",
                    catalogsearch:  "#F5861A",
                    catalog:        "#1B7B00"
                },
                datalabels : {
                    other:          "Other pages",
                    cms:            "CMS pages",
                    checkout:       "Checkout pages",
                    catalogsearch:  "Search pages",
                    catalog:        "Catalog pages"
                }
            });
        <?php endif;?>
</script>
