<?php
/**
 * @copyright  Copyright (c) 2013 AITOC, Inc. 
 * @license License agreement could be found at the root folder of this package
 */
 ?>
<?php if($system = Mage::getModel('aitloadmon/system')->getSystem()): ?>
<div><?php echo $system;?></div>
<?php else:?>
    <iframe src="<?php echo Mage::getModel('aitloadmon/system')->getSystemUrl();?>" style="width: 100%; border: medium none;"></iframe>
<?php endif;?>